language: rust
sudo: false

cache:
  - cargo

rust:
  - stable

before_script:
  # Retrieve and install latest mdbook version
  - export MDBOOK_VERSION='0.3.1' # Change to use newer version
  - mkdir $HOME/.mdbook
  - curl -L -o mdbook.tar.gz https://github.com/rust-lang-nursery/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz && tar -C $HOME/.mdbook -xzvf mdbook.tar.gz
  - rm mdbook.tar.gz
  - export PATH=$HOME/.mdbook/mdbook:$PATH

script:
  - mdbook build && mdbook test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book
  keep-history: true
  on:
    branch: src
  target-branch: master
