language: rust

before_script:
  # Retrieve and install latest mdbook version
  - misc/download-mdbook.sh 0.4.2
  - export PATH=$HOME/.mdbook:$PATH

script:
  - mdbook build && mdbook test

deploy:
  provider: pages
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: book
  keep-history: true
  on:
    branch: src
  target-branch: master
